### ISSUE TITLE
Error: Cannot find module 'Set'

### ISSUE THREAD

**Issue by jaydson** [thomasloh/5to6#3]
After install it i get this error trying to run 5to6:

module.js:338
    throw err;
          ^
Error: Cannot find module 'Set'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/jaydson/.nvm/v0.11.14/lib/node_modules/5to6/src/modules/convert-require-stmt-to-import-stmt.js:6:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/jaydson/.nvm/v0.11.14/lib/node_modules/5to6/src/index.js:10:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
jaydson@jaydson:~/Workspace/transpileption$

**Comment by thomasloh** [comment]
@jaydson just made a minor patch, please update 5to6 and try again.

``` bash
sudo npm install 5to6@latest -g
```
